Use struct PKCS11_*_private in internal APIs
OpenSC/libp11 pull request #414
Opened 2021-06-28 14:57 UTC by fabled

This is the first step to implement thread safety for the openssl engine per #410.

Things to note:

 - The public key and cert struct label/id now point to data owned
   by the private struct. This is also helpful in future to allow
   multiple public structs refer to same private struct.

 - The update_ex_data() hook is no longer needed because the private
   structs never move. Thus it is removed.

 - "evp_key" is removed from the public PKCS11_KEY. Users of it should
   be calling PKCS11_get_private_key() and PKCS11_get_public_key()
   anyway.

 - PKCS11_TOKEN no longer has private data pointer. Instead it contains
   parent pointer to PKCS11_SLOT which will be used to resolve the
   the PKCS11_TOKEN_private via PCKS11_SLOT_private. This is needed
   to make sure there's one single PKCS11_TOKEN_private even if we
   have multiple PKCS11_TOKEN copies.

@mtrojnar This is the first step. I'll make further work on top of this. But as this is fairly intrusive change, I figured it's better to get this discussed and merged first.

2022-03-20 22:02 UTC, mtrojnar requested changes
Nice work!
Add documentation and tests for the new public API functions.
Resolve merge conflicts against the current master.

2022-04-10 03:26 UTC, mtrojnar commented
@fabled Are you still interested in merging this PR?

2022-04-10 09:34 UTC, fabled commented
Yes, I'll try to do the rebase and add the documentation tomorrow. I've been on vacation and busy with various things.

2022-04-11 06:53 UTC, fabled commented on src/libp11.h
> +extern X509 *PKCS11_get_x509_from_template(PKCS11_TOKEN *, PKCS11_CERT *);
Ther other API functions return `PCKS11_CERT` objects. This one returns OpenSSL `X509`. I named this based on the return object type. But it's ok to change it if wanted.

2022-04-11 06:58 UTC, fabled commented on src/libp11.h
> +extern int PKCS11_update_slots(PKCS11_CTX * ctx,
This was in the commit message. Added to documentation now too.

2022-04-11 06:58 UTC, fabled commented on src/libp11.h
> +extern EVP_PKEY *PKCS11_get_key_from_template(PKCS11_TOKEN *, PKCS11_KEY *);
Updated.

2022-04-15 18:28 UTC, fabled commented
I did update this earlier. Not sure if the rebase / push generated notify. Please take a look again.

2022-04-22 04:43 UTC, merged

2022-05-20 11:49 UTC, fabled commented
> @fabled I reverted [206af15](https://github.com/OpenSC/libp11/commit/206af152fbcb48d4149097ed140e4840febd72d8) in [42474de](https://github.com/OpenSC/libp11/commit/42474de4de4a3f855b872ecdd4adc2e877585320), as it caused some of our tests to fail. Please consider fixing and resubmitting this commit.
> 
> Otherwise, it seems to work fine. Thank you.

I'll try to find a moment to look at it. Though, it did pass the suite when I tested it, including the CI tests. I wonder if something changed afterwards. But I'll take a look.

2022-08-09 07:07 UTC, fabled commented
> > @fabled I reverted [206af15](https://github.com/OpenSC/libp11/commit/206af152fbcb48d4149097ed140e4840febd72d8) in [42474de](https://github.com/OpenSC/libp11/commit/42474de4de4a3f855b872ecdd4adc2e877585320), as it caused some of our tests to fail. Please consider fixing and resubmitting this commit.
> > Otherwise, it seems to work fine. Thank you.
> 
> I'll try to find a moment to look at it. Though, it did pass the suite when I tested it, including the CI tests. I wonder if something changed afterwards. But I'll take a look.

I tried reproducing this, but the test suite passes just fine with the commit applied on my local check out. Any ideas?

2022-08-09 08:11 UTC, mtrojnar commented
I tried cherry-picking your commit against the current master branch and the result is:
```
=============================================
   libp11 0.4.13_git: tests/test-suite.log
=============================================

# TOTAL: 15
# PASS:  11
# SKIP:  0
# XFAIL: 0
# FAIL:  4
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: rsa-check-privkey.softhsm
===============================

Current directory: /home/mtrojnar/src/libp11/tests
Source directory: .
Output directory: output.315850
* Initializing smart card... ok
Using slot 0 with a present token (0x554d6e50)
Using slot 0 with a present token (0x554d6e50)
***************
Listing objects
***************
Using slot 0 with a present token (0x554d6e50)
Certificate Object; type = X.509 cert
  label:      server-key
  subject:    DN: CN=server-1
  ID:         01020304
Private Key Object; RSA 
  label:      server-key
  ID:         01020304
  Usage:      decrypt, sign, unwrap
  Access:     sensitive
PKCS#11: Initializing the engine: /usr/lib64/pkcs11/libsofthsm2.so
Found 2 slots
Looking in slots for private key without login:  id=01020304 label=server-key
- [1431137872] SoftHSM slot ID 0x554d6e5  login                                 (libp11-test)
- [1] SoftHSM slot ID 0x1        uninitialized, login                  (no label)
Found slot:  SoftHSM slot ID 0x554d6e50
Found token: libp11-test
Looking in slots for private key with login:  id=01020304 label=server-key
- [1431137872] SoftHSM slot ID 0x554d6e5  login                                 (libp11-test)
- [1] SoftHSM slot ID 0x1        uninitialized, login                  (no label)
Found slot:  SoftHSM slot ID 0x554d6e50
Found token: libp11-test
./rsa-check-privkey.softhsm: line 33: 315898 Segmentation fault      (core dumped) ./check-privkey ${CERTIFICATE} ${PRIVATE_KEY} ${MODULE} "${outdir}/engines.cnf"
The private key loading couldn't get the public key from the certificate
FAIL rsa-check-privkey.softhsm (exit status: 1)

FAIL: ec-check-privkey.softhsm
==============================

Current directory: /home/mtrojnar/src/libp11/tests
Source directory: .
Output directory: output.315868
* Initializing smart card... ok
Using slot 0 with a present token (0x1c81edd7)
Using slot 0 with a present token (0x1c81edd7)
***************
Listing objects
***************
Using slot 0 with a present token (0x1c81edd7)
Certificate Object; type = X.509 cert
  label:      server-key
  subject:    DN: CN=ec
  ID:         01020304
Private Key Object; EC
  label:      server-key
  ID:         01020304
  Usage:      decrypt, sign, unwrap
  Access:     sensitive
PKCS#11: Initializing the engine: /usr/lib64/pkcs11/libsofthsm2.so
Found 2 slots
Looking in slots for private key without login:  id=01020304 label=server-key
- [478277079] SoftHSM slot ID 0x1c81edd  login                                 (libp11-test)
- [1] SoftHSM slot ID 0x1        uninitialized, login                  (no label)
Found slot:  SoftHSM slot ID 0x1c81edd7
Found token: libp11-test
Looking in slots for private key with login:  id=01020304 label=server-key
- [478277079] SoftHSM slot ID 0x1c81edd  login                                 (libp11-test)
- [1] SoftHSM slot ID 0x1        uninitialized, login                  (no label)
Found slot:  SoftHSM slot ID 0x1c81edd7
Found token: libp11-test
./ec-check-privkey.softhsm: line 32: 315907 Segmentation fault      (core dumped) ./check-privkey ${CERTIFICATE} ${PRIVATE_KEY} ${MODULE} "${outdir}/engines.cnf"
The private key loading couldn't get the public key from the certificate
FAIL ec-check-privkey.softhsm (exit status: 1)

FAIL: pkcs11-uri-without-token.softhsm
======================================

Current directory: /home/mtrojnar/src/libp11/tests
Source directory: .
Output directory: output.315875
* Initializing smart card libp11-test...ok
Importing
Finished
***************
Listing objects
***************
Using slot 0 with a present token (0x3bd617)
Private Key Object; RSA 
  label:      server-key
  ID:         01020304
  Usage:      decrypt, sign, unwrap
  Access:     sensitive
Public Key Object; RSA 2048 bits
  label:      server-key
  ID:         01020304
  Usage:      encrypt, verify, wrap
  Access:     none
Certificate Object; type = X.509 cert
  label:      server-key
  subject:    DN: CN=server-1
  ID:         01020304
Detected system: linux-gnu
engine "pkcs11" set.
./pkcs11-uri-without-token.softhsm: line 57: 315908 Segmentation fault      (core dumped) openssl pkeyutl -engine pkcs11 -keyform engine -inkey "${PRIVATE_KEY}" -sign -out "${outdir}/signature.bin" -in "${outdir}/in.txt"
Failed to generate signature using PKCS#11 URI pkcs11:object=server-key;type=private;pin-value=1234
FAIL pkcs11-uri-without-token.softhsm (exit status: 1)

FAIL: search-all-matching-tokens.softhsm
========================================

Current directory: /home/mtrojnar/src/libp11/tests
Source directory: .
Output directory: output.315909
* Initializing smart card libp11-test-0...ok
Importing objects to token libp11-test-0
Finished
Private Key Object; RSA 
  label:      label-0
  ID:         01020304
  Usage:      decrypt, sign, unwrap
  Access:     sensitive
Public Key Object; RSA 2048 bits
  label:      label-0
  ID:         01020304
  Usage:      encrypt, verify, wrap
  Access:     none
Certificate Object; type = X.509 cert
  label:      label-0
  subject:    DN: CN=server-1
  ID:         01020304
* Initializing smart card libp11-test-1...ok
Importing objects to token libp11-test-1
Finished
Certificate Object; type = X.509 cert
  label:      label-1
  subject:    DN: CN=server-1
  ID:         01020304
Public Key Object; RSA 2048 bits
  label:      label-1
  ID:         01020304
  Usage:      encrypt, verify, wrap
  Access:     none
Private Key Object; RSA 
  label:      label-1
  ID:         01020304
  Usage:      decrypt, sign, unwrap
  Access:     sensitive
* Initializing smart card libp11-test-2...ok
Importing objects to token libp11-test-2
Finished
Certificate Object; type = X.509 cert
  label:      label-2
  subject:    DN: CN=server-1
  ID:         01020304
Public Key Object; RSA 2048 bits
  label:      label-2
  ID:         01020304
  Usage:      encrypt, verify, wrap
  Access:     none
Private Key Object; RSA 
  label:      label-2
  ID:         01020304
  Usage:      decrypt, sign, unwrap
  Access:     sensitive
* Initializing smart card libp11-test-3...ok
Importing objects to token libp11-test-3
Finished
Private Key Object; RSA 
  label:      label-3
  ID:         01020304
  Usage:      decrypt, sign, unwrap
  Access:     sensitive
Certificate Object; type = X.509 cert
  label:      label-3
  subject:    DN: CN=server-1
  ID:         01020304
Public Key Object; RSA 2048 bits
  label:      label-3
  ID:         01020304
  Usage:      encrypt, verify, wrap
  Access:     none
* Initializing smart card libp11-test-4...ok
Importing objects to token libp11-test-4
Finished
Public Key Object; RSA 2048 bits
  label:      label-4
  ID:         01020304
  Usage:      encrypt, verify, wrap
  Access:     none
Private Key Object; RSA 
  label:      label-4
  ID:         01020304
  Usage:      decrypt, sign, unwrap
  Access:     sensitive
Certificate Object; type = X.509 cert
  label:      label-4
  subject:    DN: CN=server-1
  ID:         01020304
* Initializing smart card libp11-test-5...ok
Importing objects to token libp11-test-5
Finished
Private Key Object; RSA 
  label:      label-5
  ID:         01020304
  Usage:      decrypt, sign, unwrap
  Access:     sensitive
Certificate Object; type = X.509 cert
  label:      label-5
  subject:    DN: CN=server-1
  ID:         01020304
Public Key Object; RSA 2048 bits
  label:      label-5
  ID:         01020304
  Usage:      encrypt, verify, wrap
  Access:     none
Detected system: linux-gnu
engine "pkcs11" set.
Multiple matching slots (6); will not try to login
- [1] SoftHSM slot ID 0x3b23c144: libp11-test-0
- [2] SoftHSM slot ID 0x4fe8af48: libp11-test-3
- [3] SoftHSM slot ID 0x51d84d7a: libp11-test-1
- [...]

2022-08-09 10:08 UTC, fabled commented
> Can you please submit a new PR so that our CI tests it?

Seems to be OpenSSL 3 related crash on atexit time cleanup. Not sure how this gets triggered.

2022-08-09 10:32 UTC, fabled commented
I suspect this is a SoftHSM2 issue or configuration of it. Sadly, the commit seems to expose it further. I also saw some underministic behavior: sometimes some test suites tests failed and sometimes not. The problem is likely the `atexit` handlers running in unspecified order. Also, SoftHSM2 Botan build seems to fail unconditionally.
The commit works perfectly against OpenSSL 1.1, with SoftHSM2 built against same OpenSSL.

I suspect the automatic clean up on atexit in OpenSSL 3 might be triggering this.