Introduce keypair generation as engine ctrl command
OpenSC/libp11 pull request #474
Opened 2022-09-08 13:32 UTC by istepic

becuase it's difficult (or impossible) to generate keys with native OpenSSL ENGINE interface.

2022-10-05 07:34 UTC, istepic commented
Hello @mtrojnar, does this approach to key generation seem plausible _at all_ to you?

2022-11-02 13:59 UTC, ldts commented
what is the status of this PR? has it been abandoned as well? It seems there was a previous attempt at implementing EC keygen which didn't prosper either (https://github.com/OpenSC/libp11/pull/379).

is there are reason not to pursue either of them?

2022-11-03 01:01 UTC, dengert commented
> what is the status of this PR? has it been abandoned as well? It seems there was a previous attempt at implementing EC keygen which didn't prosper either (https://github.com/OpenSC/libp11/pull/379).

is there are reason not to pursue either of them?

IMHO biggest issue with both of these is when will OpenSSL drops engine support and what happens to libp11.

2022-11-10 21:31 UTC, mwasilew commented
Is there an alternative way of generating EC key pairs on the token? It is currently possible to generate EC keys with pkcs11-tool, but not libp11 API.

2022-11-14 17:46 UTC, istepic commented
> Is there an alternative way of generating EC key pairs on the token? It is currently possible to generate EC keys with pkcs11-tool, but not libp11 API.

No alternative way for EC keys.

2024-12-02 20:26 UTC, mtrojnar commented
The engine interface looks good to me.

On the other hand, changing the definition of `PKCS11_generate_key()` is unacceptable, because it breaks each and every existing function that uses that API function.  You need to define a new API function instead (e.g., `PKCS11_keygen()`) and reimplement the existing `PKCS11_generate_key()` API function as a wrapper for the new `PKCS11_keygen()`.

2025-02-09 16:08 UTC, rafajunio commented
Hello @mtrojnar , can you please check if the PR is good for you now? 

I requested Ivan access for change the patch.

I do not known what to do with the hex_to_bin in the p11_front.c, but I do not want to introduce even more changes to the PR.

2025-02-10 20:43 UTC, mtrojnar commented
@rafajunio

The API looks better now.  I think it should be possible to merge this feature.

@olszomal and myself are in the middle of implementing PKCS#11 provider. More internal changes in PIN UI will be implemented soon.  Please wait a few weeks for the code changes to stabilize, and then I'll ask you to rebase your PR on top of the new code.  What do you think?

2025-03-26 23:37 UTC, rafajunio commented
@mtrojnar 
I tried to refactor as much as possible, I also tried to create the provider test already but I could not. Either way I upload the code for you start the review, if you have some hint please let me known

2025-04-02 12:25 UTC, olszomal requested changes
Excellent work – the code is clean and well-structured, making it easy to review.

I confirm that key pair generation works correctly for both the libp11 library and the engine.

Unfortunately, the OpenSSL provider currently only supports retrieving objects from the token, meaning it cannot be used for key generation. Please remove the key generation test for the provider.

2025-04-02 12:25 UTC, olszomal commented on tests/keygen.c
> +
Remember to call EVP_PKEY_free()

2025-04-02 12:25 UTC, olszomal commented on tests/keygen.c
> +	PKCS11_EC_KGEN ec = {
Declare structures and variables at the beginning of the code block, following the C89/C90 standard.

2025-04-02 12:25 UTC, olszomal commented on tests/keygen.c
> +	 * RSA key generation test
Split the test into two separate cases for RSA and EC key generation to maintain consistency with existing tests.

2025-04-02 12:25 UTC, olszomal commented on src/eng_back.c
> +	// Try with logging in
This project uses C-style comments instead of C++.

2025-04-02 12:25 UTC, olszomal commented on tests/keygen-prov.c
> +	if (!providers_load()) {
Unfortunately, the OpenSSL provider currently only supports retrieving objects from the token, meaning it cannot be used for key generation.
Please remove the key generation test for the provider.

2025-04-02 12:25 UTC, olszomal commented on src/util.h
> +int UTIL_CTX_get_force_login(UTIL_CTX *ctx);
Remove the unused function UTIL_CTX_get_force_login().

2025-04-03 12:30 UTC, olszomal requested changes
Generally well done! Some minor style tweaks, but also a significant issue that needs attention.

2025-04-03 12:30 UTC, olszomal commented on src/eng_back.c
> +	if (found_slot->token->loginRequired && UTIL_CTX_login(ctx->util_ctx,
If token login is required, UTIL_CTX_login() must be called. However, try to generate a key pair.

2025-04-03 12:30 UTC, olszomal commented on src/p11_key.c
> +	// convert to DER format and take just the length
Use C-style comments instead of C++. This note applies to all comments; sorry for the confusion.

2025-04-03 12:30 UTC, olszomal commented on tests/Makefile.am
> +keygen_prov_SOURCES = keygen-prov.c helpers_prov.c
Unused

2025-04-03 12:30 UTC, olszomal commented on tests/ec-keygen.c
> +	printf("ECC Sign-verify success\n");
Formally, it should be EC keys instead of ECC keys, as EC refers specifically to Elliptic Curve keys, while ECC refers to the broader field of Elliptic Curve Cryptography.

2025-04-03 12:30 UTC, olszomal commented on src/libp11-int.h
> +	size_t id_len, const PKCS11_params* params);
Please use `TYPE *ptr` instead of `TYPE* ptr` to follow the project's convention.

2025-04-04 07:30 UTC, olszomal requested changes

2025-04-04 07:30 UTC, olszomal commented on tests/ec-keygen.c
> +	if (!engine)
This condition is incorrect.
ENGINE_finish(engine) should be called unconditionally to release the functional reference obtained via ENGINE_init(). Please remove the if statement and call ENGINE_finish(engine); directly. Skipping it when engine == NULL is safe, as the function handles that internally.

2025-04-04 07:30 UTC, olszomal commented on tests/rsa-keygen.c
> +	if (!engine)
The condition is incorrect.

2025-04-04 09:38 UTC, olszomal approved these changes
Looks good — thanks for the changes!
I’ll take care of the small style issue separately to keep things moving.

2025-04-04 10:00 UTC, merged

2025-11-19 08:39 UTC, proxyrer commented on src/p11_key.c
> +	CK_BYTE public_exponent[] = { 1, 0, 0, 0, 1 };
Interesting! So the value is indeed a valid exponent? Sorry, I'm not too well-versed in cryptography. It seems then that the real limitation that got me here is that the software I use that signs the CSR does not support large public key exponents. Is there a way to specify desired public key exponent in libp11 during key generation? Also let me know if you'd rather I open an issue to move this discussion elsewhere.

2025-11-19 09:03 UTC, mtrojnar commented on src/p11_key.c
> +	CK_BYTE public_exponent[] = { 1, 0, 0, 0, 1 };
@istepic Would you kindly share your rationale for changing `{ 1, 0, 1 }` to `{ 1, 0, 0, 0, 1 }`?